import { useState } from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CartSidebar from "@/components/CartSidebar";
import { Toaster } from "@/components/ui/toaster";
import { ScrollAnimation } from "@/components/ScrollAnimations";
import { useSEO } from "@/hooks/useSEO";
import { seoConfig } from "@/config/seo";

const TermsAndConditions = () => {
    const [isCartOpen, setIsCartOpen] = useState(false);

    useSEO(seoConfig.pages.terms);

    return (
        <div className="min-h-screen overflow-x-hidden">
            <Header onCartClick={() => setIsCartOpen(true)} />
            <div className="pt-24">
                <div className="container mx-auto px-4 py-8 max-w-5xl">
                    <div className="text-center mb-10">
                        <h1 className="text-4xl md:text-5xl font-bold font-poppins text-warmBrown mb-3">
                            Terms & Conditions
                        </h1>
                        <p className="text-warmBrown/80 font-merriweather">
                            Please read these terms carefully before using our
                            Platform.
                        </p>
                    </div>

                    <ScrollAnimation direction="up" delay={150}>
                        <div className="space-y-6 text-warmBrown/90 font-merriweather leading-relaxed">
                            <p>
                                This document is an electronic record in terms
                                of the Information Technology Act, 2000 and
                                rules thereunder as applicable and the amended
                                provisions pertaining to electronic records in
                                various statutes as amended by the Information
                                Technology Act, 2000. This electronic record is
                                generated by a computer system and does not
                                require any physical or digital signatures.
                            </p>
                            <p>
                                This document is published in accordance with
                                Rule 3(1) of the Information Technology
                                (Intermediaries Guidelines) Rules, 2011
                                requiring publication of the rules and
                                regulations, privacy policy, and terms of use
                                for access or usage of the domain name{" "}
                                <strong>
                                    https://www.namoindianamkeen.com
                                </strong>{" "}
                                ("Website"), including any related mobile site
                                and mobile application (collectively, the
                                "Platform").
                            </p>
                            <p>
                                The Platform is owned by{" "}
                                <strong>Namo India Food Industries</strong>{" "}
                                ("Platform Owner", "we", "us", "our"), with its
                                registered office at 65-A, Nagin Nagar, Indore,
                                Madhya Pradesh, India.
                            </p>
                            <p>
                                Your use of the Platform and services and tools
                                are governed by the following terms and
                                conditions ("Terms of Use") including applicable
                                policies incorporated herein by reference. By
                                mere use of the Platform, you shall be
                                contracting with the Platform Owner and these
                                Terms of Use constitute your binding
                                obligations.
                            </p>
                            <p className="font-semibold">
                                ACCESSING, BROWSING OR OTHERWISE USING THE
                                PLATFORM INDICATES YOUR AGREEMENT TO ALL THE
                                TERMS AND CONDITIONS UNDER THESE TERMS OF USE.
                                PLEASE READ THESE TERMS CAREFULLY BEFORE
                                PROCEEDING.
                            </p>

                            <h2 className="text-2xl font-semibold text-warmBrown pt-4">
                                Use of Platform
                            </h2>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>
                                    To access and use the Services, you agree to
                                    provide true, accurate and complete
                                    information during and after registration
                                    and are responsible for all acts done
                                    through your registered account.
                                </li>
                                <li>
                                    Neither we nor any third parties provide any
                                    warranty or guarantee as to the accuracy,
                                    timeliness, performance, completeness or
                                    suitability of information and materials
                                    offered on the Platform for any specific
                                    purpose. You acknowledge such information
                                    may contain inaccuracies or errors and we
                                    expressly exclude liability for such
                                    inaccuracies to the fullest extent permitted
                                    by law.
                                </li>
                                <li>
                                    Your use of the Platform and Services is at
                                    your own risk and discretion. You must
                                    independently assess and ensure that the
                                    Services meet your requirements.
                                </li>
                                <li>
                                    The contents of the Platform and the
                                    Services are proprietary to or licensed to
                                    us. You will not claim any intellectual
                                    property rights, title, or interest in the
                                    contents, including design, layout, look,
                                    and graphics.
                                </li>
                                <li>
                                    Unauthorized use of the Platform and/or
                                    Services may give rise to a claim for
                                    damages and/or be a criminal offence.
                                </li>
                                <li>
                                    You agree to pay the charges associated with
                                    availing the Services, as applicable.
                                </li>
                                <li>
                                    You agree not to use the Platform and/or
                                    Services for any purpose that is unlawful or
                                    prohibited by these Terms or by applicable
                                    laws.
                                </li>
                                <li>
                                    The Platform may contain links to
                                    third-party websites. On accessing these
                                    links, you will be governed by the terms of
                                    use and privacy policies of such third-party
                                    websites. These links are provided for your
                                    convenience.
                                </li>
                                <li>
                                    By initiating a transaction for availing
                                    Services, you enter into a legally binding
                                    and enforceable contract with the Platform
                                    Owner.
                                </li>
                            </ul>

                            <h2 className="text-2xl font-semibold text-warmBrown pt-4">
                                Indemnity
                            </h2>
                            <p>
                                You shall indemnify and hold harmless the
                                Platform Owner, its affiliates and group
                                companies and their respective officers,
                                directors, agents, and employees from any claim,
                                demand, actions, penalties, including reasonable
                                attorneys' fees, arising out of your breach of
                                these Terms of Use, Privacy Policy, other
                                policies, violation of law, or infringement of
                                third-party rights.
                            </p>

                            <h2 className="text-2xl font-semibold text-warmBrown pt-4">
                                Force Majeure
                            </h2>
                            <p>
                                Notwithstanding anything contained herein,
                                neither party shall be liable for any failure to
                                perform obligations if such performance is
                                prevented or delayed by a force majeure event.
                            </p>

                            <h2 className="text-2xl font-semibold text-warmBrown pt-4">
                                Governing Law and Jurisdiction
                            </h2>
                            <p>
                                These Terms and any dispute relating to them
                                shall be governed by and construed in accordance
                                with the laws of India. All disputes arising out
                                of these Terms shall be subject to the exclusive
                                jurisdiction of the courts.
                            </p>

                            <h2 className="text-2xl font-semibold text-warmBrown pt-4">
                                Refunds, Returns, and Exchanges
                            </h2>
                            <p>
                                We do not offer any kind of refund, return, or
                                exchange. All sales are final.
                            </p>

                            <h2 className="text-2xl font-semibold text-warmBrown pt-4">
                                Contact
                            </h2>
                            <p>
                                All concerns or communications relating to these
                                Terms must be sent using the contact information
                                provided on this website.
                            </p>
                        </div>
                    </ScrollAnimation>
                </div>
            </div>
            <Footer />
            <CartSidebar
                isOpen={isCartOpen}
                onClose={() => setIsCartOpen(false)}
            />
            <Toaster />
        </div>
    );
};

export default TermsAndConditions;
