// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zonrpmwwbclmvcekuxlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvbnJwbXd3YmNsbXZjZWt1eGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTQzNDIsImV4cCI6MjA2MzczMDM0Mn0.NSZk_hKZk8SBzXvwZNMCBcNEB7OvVgb8Fu8Gi9a0hno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);